<a href="https://colab.research.google.com/github/warrensuca/chinese-recipe-api/blob/main/omnivores_cookbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Omnivore's Cookbook Scraper
This notebook scrapes recipe data from the Omnivore's Cookbook Website: https://www.chinasichuanfood.com/

For each recipe, we collect:

- Name
- Ingredients Full List
- Ingredients Names List
  - Used in clustering, very difficult to parse from full list
- Procedure
- Nutrition Facts

The final dataset is stored as a Pandas DataFrame and exported to CSV.

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from IPython.display import display
import time
print("setup complete")

setup complete

In [ ]:
session = requests.Session()

session.headers.update({
    "User-Agent":
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
})

print("Session initialized")

Session initialized

#Scrape individual recipe URL
Exploration. Later, we will turn this into a function

In [22]:

url = "https://omnivorescookbook.com/black-pepper-chicken/"
headings = [
      "Name",
      "Ingredients_List",
      "Ingredients_Names",
      "Procedure",
      "Nutrition_Facts"
  ]

response = session.get(url, timeout=10)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")

recipe_data = {
    "Name": url.split("/")[-2] #getting title is an additional call, just clean later
}
print(recipe_data["Name"])
print('\n')

ingredients_list_raw = soup.find_all("li", class_ = "wprm-recipe-ingredient")
ingredients_list = []

for ingredient in ingredients_list_raw:
  ingredients_list.append(ingredient.get_text()) #remove a bullet point svg

print(ingredients_list)
print('\n')
recipe_data["Ingredients_List"] = ingredients_list

ingredients_names_raw = soup.find_all("span", class_ = "wprm-recipe-ingredient-name")
ingredients_names = []

for ingredient_name in ingredients_names_raw:
  ingredients_names.append(ingredient_name.get_text())

print(ingredients_names)
print('\n')
recipe_data["Ingredients_Names"] = ingredients_names

procedure_list_raw = soup.find_all("li", class_ = "wprm-recipe-instruction")
procedure_list = []

for procedure in procedure_list_raw:
  procedure_list.append(procedure.get_text())

print(procedure_list)
print('\n')
recipe_data["Procedure"] = procedure_list

nutrition_facts_list_raw = soup.find_all("span", class_ = "wprm-nutrition-label-text-nutrition-container")
nutrition_facts = []
for nutrition_fact in nutrition_facts_list_raw:
  #print(nutrition_fact.get_text())
  nutrition_facts.append(nutrition_fact.get_text())

print(nutrition_facts)

recipe_data["Nutrition_Facts"] = nutrition_facts

black-pepper-chicken


['1 lb chicken breasts (or thighs) , sliced against the grain into 1/4” (5-mm) thick pieces', '1 tablespoon light soy sauce (or soy sauce)', '1 tablespoon Shaoxing wine (or dry sherry)', '1 tablespoon cornstarch', '1/2 cup chicken broth', '2 tablespoons light soy sauce (or soy sauce)', '2 tablespoons Shaoxing wine (or dry sherry)', '2 teaspoons dark soy sauce (or soy sauce)', '1 tablespoon cornstarch', '1 1/2 tablespoons sugar', '2 teaspoons coarsely ground black pepper', '1/8 teaspoon salt', '2 tablespoons peanut oil (or vegetable oil)', '1 tablespoon minced ginger', '2 cloves garlic , minced', '1/2 white onion , chopped', '2 bell peppers , chopped (I used mixed colors)']


['chicken breasts (or thighs)', 'light soy sauce', 'Shaoxing wine', 'cornstarch', 'chicken broth', 'light soy sauce', 'Shaoxing wine', 'dark soy sauce', 'cornstarch', 'sugar', 'coarsely ground black pepper', 'salt', 'peanut oil', 'minced ginger', 'garlic', 'white onion', 'bell peppers']


['Combine chicken, soy sauce, Shaoxing wine, and cornstarch in a medium-sized bowl. Gently mix by hand until the chicken is coated with a thin layer of the mixture. Marinate for 10 to 15 minutes.', 'Combine all the sauce ingredients in a small bowl. Mix well and set aside.', 'Heat 1 tablespoon of oil in a large skillet over medium-high heat until hot. Add the chicken. Immediately spread the chicken into a single layer using a spatula, with as little overlap as possible. Sear for 1 minute or so, until the bottom is lightly browned. Flip the chicken. Cook for 30 seconds to 1 minute. Stir occasionally, until both sides are browned but still a bit pink inside. Transfer the chicken to a plate and set aside.', 'Add the remaining 1 tablespoon of oil to the skillet. Add the ginger and garlic. Give it a quick stir until fragrant. Add the white onion and peppers. Stir and cook for 20 seconds.', 'Stir the sauce mixture until the cornstarch is dissolved completely, and pour it into the skillet. Stir with a spatula immediately and cook until the sauce thickens enough to coat the back of a spoon, a few seconds. Add back the cooked chicken. Quickly stir a few times to coat everything with the sauce. Turn off heat and remove the skillet from the stove. Immediately transfer everything to a big plate so the ingredients won’t keep cooking in the hot skillet.', 'Serve hot as a main dish.']


['Serving: 1serving', 'Calories: 269kcal', 'Carbohydrates: 17.8g', 'Protein: 26.1g', 'Fat: 10g', 'Saturated Fat: 1.2g', 'Cholesterol: 73mg', 'Sodium: 674mg', 'Potassium: 607mg', 'Fiber: 1.3g', 'Sugar: 9.4g', 'Calcium: 20mg', 'Iron: 1mg']

#Create function based off exploration
This function will be used on each recipe of the site

In [23]:
def scrape_recipe(url: str):


  response = session.get(url, timeout=10)
  response.raise_for_status()

  soup = BeautifulSoup(response.text, "html.parser")

  recipe_data = {
      "Name": url.split("/")[-2] #getting title is an additional call, just clean later
  }


  ingredients_list_raw = soup.find_all("li", class_ = "wprm-recipe-ingredient")
  ingredients_list = []

  for ingredient in ingredients_list_raw:
    ingredients_list.append(ingredient.get_text()) #remove a bullet point svg


  recipe_data["Ingredients_List"] = ingredients_list


  ingredients_names_raw = soup.find_all("span", class_ = "wprm-recipe-ingredient-name")
  ingredients_names = []

  for ingredient_name in ingredients_names_raw:
    ingredients_names.append(ingredient_name.get_text())

  recipe_data["Ingredients_Names"] = ingredients_names


  procedure_list_raw = soup.find_all("li", class_ = "wprm-recipe-instruction")
  procedure_list = []

  for procedure in procedure_list_raw:
    procedure_list.append(procedure.get_text())



  recipe_data["Procedure"] = procedure_list

  nutrition_facts_list_raw = soup.find_all("span", class_ = "wprm-nutrition-label-text-nutrition-container")
  nutrition_facts = []
  for nutrition_fact in nutrition_facts_list_raw:
    #print(nutrition_fact.get_text())
    nutrition_facts.append(nutrition_fact.get_text())

  recipe_data["Nutrition_Facts"] = nutrition_facts

  return recipe_data

In [ ]:
recipe_data = scrape_recipe("https://omnivorescookbook.com/black-pepper-chicken/")

recipe_data

{'Name': 'black-pepper-chicken',
 'Ingredients_List': ['1 lb chicken breasts (or thighs) , sliced against the grain into 1/4” (5-mm) thick pieces',
  '1 tablespoon light soy sauce (or soy sauce)',
  '1 tablespoon Shaoxing wine (or dry sherry)',
  '1 tablespoon cornstarch',
  '1/2 cup chicken broth',
  '2 tablespoons light soy sauce (or soy sauce)',
  '2 tablespoons Shaoxing wine (or dry sherry)',
  '2 teaspoons dark soy sauce (or soy sauce)',
  '1 tablespoon cornstarch',
  '1 1/2 tablespoons sugar',
  '2 teaspoons coarsely ground black pepper',
  '1/8 teaspoon salt',
  '2 tablespoons peanut oil (or vegetable oil)',
  '1 tablespoon minced ginger',
  '2 cloves garlic , minced',
  '1/2 white onion , chopped',
  '2 bell peppers , chopped (I used mixed colors)'],
 'Ingredients_Names': ['chicken breasts (or thighs)',
  'light soy sauce',
  'Shaoxing wine',
  'cornstarch',
  'chicken broth',
  'light soy sauce',
  'Shaoxing wine',
  'dark soy sauce',
  'cornstarch',
  'sugar',
  'coarsely ground black pepper',
  'salt',
  'peanut oil',
  'minced ginger',
  'garlic',
  'white onion',
  'bell peppers'],
 'Procedure': ['Combine chicken, soy sauce, Shaoxing wine, and cornstarch in a medium-sized bowl. Gently mix by hand until the chicken is coated with a thin layer of the mixture. Marinate for 10 to 15 minutes.',
  'Combine all the sauce ingredients in a small bowl. Mix well and set aside.',
  'Heat 1 tablespoon of oil in a large skillet over medium-high heat until hot. Add the chicken. Immediately spread the chicken into a single layer using a spatula, with as little overlap as possible. Sear for 1 minute or so, until the bottom is lightly browned. Flip the chicken. Cook for 30 seconds to 1 minute. Stir occasionally, until both sides are browned but still a bit pink inside. Transfer the chicken to a plate and set aside.',
  'Add the remaining 1 tablespoon of oil to the skillet. Add the ginger and garlic. Give it a quick stir until fragrant. Add the white onion and peppers. Stir and cook for 20 seconds.',
  'Stir the sauce mixture until the cornstarch is dissolved completely, and pour it into the skillet. Stir with a spatula immediately and cook until the sauce thickens enough to coat the back of a spoon, a few seconds. Add back the cooked chicken. Quickly stir a few times to coat everything with the sauce. Turn off heat and remove the skillet from the stove. Immediately transfer everything to a big plate so the ingredients won’t keep cooking in the hot skillet.',
  'Serve hot as a main dish.'],
 'Nutrition_Facts': ['Serving: 1serving',
  'Calories: 269kcal',
  'Carbohydrates: 17.8g',
  'Protein: 26.1g',
  'Fat: 10g',
  'Saturated Fat: 1.2g',
  'Cholesterol: 73mg',
  'Sodium: 674mg',
  'Potassium: 607mg',
  'Fiber: 1.3g',
  'Sugar: 9.4g',
  'Calcium: 20mg',
  'Iron: 1mg']}

#Scrape single page
Exploration

In [ ]:
page = 3

response = session.get("https://omnivorescookbook.com/category/recipe/?_paged={}".format(page), timeout=10)
response.raise_for_status()

data = []

soup = BeautifulSoup(response.text, "html.parser")

recipes = soup.find_all(class_ = "gridtitle")


for recipe in recipes[:5]:

  data.append(scrape_recipe(recipe.a.get("href")))
data

[{'Name': 'bok-choy-with-oyster-sauce',
  'Ingredients_List': ['1 lb baby bok choy',
   '1 tablespoon peanut oil (or vegetable oil)',
   '2 dried chili peppers',
   '2 teaspoons ginger , minced',
   '1/2 teaspoon sugar',
   '1 tablespoon soy sauce',
   '2 tablespoons oyster sauce'],
  'Ingredients_Names': ['baby bok choy',
   'peanut oil',
   'dried chili peppers',
   'ginger',
   'sugar',
   'soy sauce',
   'oyster sauce'],
  'Procedure': ['Cut off the ends of baby bok choy and discard. Separate the larger leaves of baby bok choy. Soak in cold water for 2 minutes, then rinse to remove any dust. Cut the stems into 1/2” pieces and the leaves into 2” pieces. Separate the whites and greens. Halve the cores.',
   'Heat oil in a wok over medium-high heat until smoking. Add chili peppers and ginger. Stir a few times to release fragrance.',
   'Add the baby bok choy whites and turn to high heat. Stir a few times to coat evenly with oil, spread them out and sear until the white part just starts to turn tender, 1 to 2 minutes.',
   'Add the baby bok choy greens and sprinkle with sugar. Stir to mix well. Add the soy sauce and oyster sauce. Stir immediately to mix the ingredients. Cook and stir until the greens are wilted, then transfer everything to a big serving plate. Serve hot as a side dish.'],
  'Nutrition_Facts': ['Serving: 1serving',
   'Calories: 65kcal',
   'Carbohydrates: 6.3g',
   'Protein: 3.5g',
   'Fat: 3.9g',
   'Saturated Fat: 0.7g',
   'Sodium: 417mg',
   'Potassium: 551mg',
   'Fiber: 2.3g',
   'Sugar: 3.1g',
   'Calcium: 223mg',
   'Iron: 2mg']},
 {'Name': 'salt-and-pepper-squid',
  'Ingredients_List': ['1 1/2 lbs baby squid',
   '6 cups vegetable oil , for frying',
   '1 batch basil  , for garnish (Optional)',
   '4 to 5  Thai chili peppers  , for garnish (Optional)',
   '2 tablespoons Shaoxing wine',
   '1/4 teaspoon salt',
   '2 tablespoons minced ginger',
   '2 cloves garlic , minced',
   '1/3 cup all-purpose flour (*footnote 1)',
   '1/3 cup cornstarch',
   '1/4 cup cornmeal',
   '1/2 teaspoon salt',
   '1/2 teaspoon white pepper',
   'Lemon wedges',
   'Mayonnaise , ketchup, Sriracha hot sauce, wasabi mayo, or mustard as dipping sauce'],
  'Ingredients_Names': ['baby squid',
   'vegetable oil',
   'basil ',
   'Thai chili peppers ',
   'Shaoxing wine',
   'salt',
   'minced ginger',
   'garlic',
   'all-purpose flour',
   'cornstarch',
   'cornmeal',
   'salt',
   'white pepper',
   'Lemon wedges',
   'Mayonnaise'],
  'Procedure': ['Rinse squid with running water and drain. Slice the cap into 1/3-inch (1 cm) rings and leave the tentacles in one piece. If you use larger squid, you can slice the tentacles into 2-inch (4 cm) bite size pieces.',
   'Transfer everything into a big bowl and add marinate ingredients. Mix thoroughly by hand. Mariante in the fridge for at least 15 minutes to up to 1 hour.',
   'Meanwhile mix all the ingredients for the dry coating in a big bowl.',
   'When you’re ready to cook, add 2 to 3 inches (5 to 7 cm) oil in a medium-size deep pot. Heat over medium-high heat until the oil reaches 375 to 400 degrees F (190 to 200°C). If you do not have a thermometer, place a clean bamboo chopstick into the oil. You should see small bubbles rapidly form around the chopstick. Turn to medium heat.',
   'While heating up the oil, set up the deep fry station by placing a large wire rack on a big tray. Or you can use a few plates instead. (*Footnote 2)',
   'Drain the squid and discard the liquid. Transfer half of the coating and a half of the squid into a large ziplock bag. Shake and the bag to coat the squid well. Then transfer everything into a big bowl.',
   'Separate the squid pieces and place them on a large spider sieve or slotted spoon. Lower into the hot oil. Add in small batches at a time so your pot won’t become crowded. Fry until the squid turns golden brown, 2 to 3 minutes. Transfer to the prepared wire rack. Continue to cook the remaining batches using the same method.',
   '(Optional) If you want to present the dish like in a restaurant, fry basil leaves and chili peppers for garnish. Dry them thoroughly and lower them into the oil using a sieve. This step might cause splatter since the basil contains a lot of liquid. Fry for 30 seconds, or until the basil leaves turn dark and crispy. Transfer to a plate to cool.',
   'Serve the squid hot with lemon wedges on the side. You can also serve sauces such as mayonnaise, ketchup, Sriracha, and/or mustard if you prefer. Be prepared for the wows from your family when they see you can cook salt and pepper squid like a professional chef!'],
  'Nutrition_Facts': ['Serving: 1of 4 servings',
   'Calories: 348kcal',
   'Carbohydrates: 27.8g',
   'Protein: 27.6g',
   'Fat: 12.5g',
   'Sodium: 296mg',
   'Potassium: 77mg',
   'Fiber: 1.3g',
   'Sugar: 0.2g']},
 {'Name': 'chinese-turnip-cake',
  'Ingredients_List': ['4  shiitake mushrooms',
   '2 tablespoons dried shrimp (or dried scallops)',
   '2 lbs daikon radish , peeled and grated coarsely, yields 1 lb 4 oz (560 g) grated (*Footnote 1)',
   '3 Chinese sausages , small diced into 1/3” pieces (*Footnote 2)',
   '1 teaspoon sugar',
   '3/4 teaspoon salt',
   '1/2 teaspoon white pepper',
   '1 1/4 cups rice flour',
   'Sliced scallion for garnish (Optional)',
   'Soy sauce , for serving (Optional)',
   'Chili garlic sauce (or Chinese chili crisp), for serving (Optional)'],
  'Ingredients_Names': ['shiitake mushrooms',
   'dried shrimp',
   'daikon radish',
   'Chinese sausages',
   'sugar',
   'salt',
   'white pepper',
   'rice flour',
   'Sliced scallion for garnish',
   'Soy sauce',
   'Chili garlic sauce'],
  'Procedure': ['Soak dried ingredients: Rinse the shiitake mushrooms and dried shrimp separately with tap water and gently rub them to remove any dirt. Place each ingredient into a different bowl. Add warm water to cover. Soak for 15 minutes, or until the ingredients turn soft. Drain thoroughly. Dice mushroom cap into 1/4” pieces and mince the shrimp.',
   'Cook the filling: Add the Chinese sausage into a large nonstick skillet and heat it over medium heat. Cook from a cold pan and turn to medium-low heat once the sausage starts to sizzle. Cook until the sausage is lightly browned and some oil is rendered off, 5 minutes or so. Transfer the sausage to a bowl and reserve the rendered fat. Add the shiitake mushrooms and dried shrimp. Cook and stir until lightly charred. Transfer to the same bowl with the sausage.',
   'Cook the daikon: Add the daikon radish and 1 cup of water into the same skillet. Cook over medium-high heat until simmering. Cover, simmer over medium-low heat until the daikon is soft and translucent, 8 to 10 minutes.',
   'Create the batter: Strain the cooked radish over a colander, pressing out as much liquid as you can into a big bowl or measuring cup. Measure out 1 cup of liquid, pour into a large bowl. Add rice flour, sugar, salt and white pepper. Stir to mix well until forming a very runny batter. Add back the radish and mix again.',
   'Cook the batter: Transfer the radish mixture to a large, clean nonstick skillet. Cook over medium-low heat and stir constantly, until the mixture has slightly thickened. When you stir the mixture, the radish should be able to form a clump without looking too runny. Stir in the cooked filling.',
   'Assemble: Prepare 1 to 2 glass tupperware or baking dishes that can fit into your steamer. You can use two 4.5” x 4.5” (11cm x 11 cm) tupperware dishes to cook two batches. If you have a large wok or steamer, you might be able to fit a 5” x 9” (13cm x 23cm) loaf pan or 7”x7” (20cm x 20cm) baking pan (*Footnote 3). You’ll only need to cook one batch in this case. If you’ll be cooking in two batches, cover the uncooked batter with plastic wrap to prevent it from drying out. Grease the glass tupperware with oil. Transfer the mixture into the tupperware.',
   'Steam: Set up your steamer by adding plenty of water and bringing it to a boil (*Footnote 4). Add the steaming rack with the turnip cake container. Steam over medium-high heat for 50 to 60 minutes until the turnip cake is cooked through. Test the doneness by inserting a knife into the cake and it should come out clean.',
   'Rest: Remove the steamed turnip cake and set it aside to cool. Once the container is no longer hot, transfer it to the fridge. Let the turnip cake set until it has cooled completely. (*Footnote 5)',
   'Release: Use a knife to loosen the edges from the container, then turn the container upside down. The turnip cake should come out in one piece.',
   'Serve: Cut the turnip cake into 1/4” (1 cm) thick pieces. Heat a skillet coated with a thin layer of oil, cook both sides over medium or medium low heat until heated through and the surface turns golden. Garnish with sliced green onion if using. Serve with soy sauce and chili garlic sauce, if desired.',
   'Store: Transfer the steamed turnip cakes (without pan-frying) into an airtight container and store them in the fridge for 2 to 3 days, or in the freezer for up to 1 month. To reheat, thaw the frozen turnip cakes first, and pan fry them before serving.'],
  'Nutrition_Facts': ['Serving: 1serving',
   'Calories: 170kcal',
   'Carbohydrates: 25.5g',
   'Protein: 7g',
   'Fat: 5g',
   'Saturated Fat: 1.6g',
   'Cholesterol: 19mg',
   'Sodium: 559mg',
   'Potassium: 282mg',
   'Fiber: 2.9g',
   'Sugar: 3.4g',
   'Calcium: 14mg',
   'Iron: 1mg']},
 {'Name': 'spicy-cucumber-salad',
  'Ingredients_List': ['5 to 6  mini cucumbers',
   '1/2 teaspoon salt',
   '2 tablespoons rice vinegar',
   '1 teaspoon light soy sauce',
   '1 clove garlic , minced',
   '1 teaspoon sugar',
   '1 tablespoon chili oil (use less if you prefer a less spicy dish)',
   '1 teaspoon white toasted sesame seeds'],
  'Ingredients_Names': ['mini cucumbers',
   'salt',
   'rice vinegar',
   'light soy sauce',
   'garlic',
   'sugar',
   'chili oil',
   'white toasted sesame seeds'],
  'Procedure': ['Cut and discard the ends of the cucumbers. Place one cucumber between two disposable chopsticks. Make thin diagonal slices at a 45 degree angle. Then flip the cucumber over and do the same on the other side. Then halve the cucumber crosswise. Cut the rest of the cucumbers the same way, then transfer to a large bowl. ',
   'Add the salt and toss thoroughly with your hands. Leave the salt on for 15 minutes or so, to draw out water. ',
   'Once done, rinse cucumbers and discard the water. Drain thoroughly and lightly pat the cucumbers dry.',
   'Mix the dressing ingredients in a small bowl.',
   'Right before serving, pour the sauce over and mix well. If not served immediately, the cucumbers will keep releasing water. Drain the water before mixing the sauce. Serve at room temperature as an appetizer or side.'],
  'Nutrition_Facts': ['Serving: 1serving',
   'Calories: 45kcal',
   'Carbohydrates: 2.3g',
   'Protein: 0.3g',
   'Fat: 3.5g',
   'Saturated Fat: 0.5g',
   'Sodium: 223mg',
   'Potassium: 43mg',
   'Fiber: 0.2g',
   'Sugar: 1.5g',
   'Calcium: 6mg']},
 {'Name': 'char-siu-chicken',
  'Ingredients_List': ['2 lbs bone-in skin-on chicken thighs (*Footnote 1)',
   '2 pieces red fermented tofu (or 2 tablespoons soy sauce) (Footnote 2)',
   '2 tablespoons liquid from fermented tofu (or 3/4 teaspoon salt)',
   '2 tablespoons Shaoxing wine (or dry sherry)',
   '2 tablespoons hoisin sauce',
   '2 tablespoons oyster sauce',
   '2 tablespoons sugar',
   '2 tablespoons honey',
   '2 teaspoons grated ginger',
   '2 teaspoons garlic , grated',
   '1/2 teaspoon five spice powder',
   '5 drops red food coloring (Optional, can be used if not using red fermented tofu)'],
  'Ingredients_Names': ['bone-in skin-on chicken thighs',
   'red fermented tofu',
   'liquid from fermented tofu',
   'Shaoxing wine',
   'hoisin sauce',
   'oyster sauce',
   'sugar',
   'honey',
   'grated ginger',
   'garlic',
   'five spice powder',
   'red food coloring'],
  'Procedure': ['Combine all the sauce ingredients in a large bowl. Stir to mix well.',
   'Transfer the chicken into a large ziplock bag. Reserve 1/4 cup of the mixed sauce for glazing. Pour the rest into the bag. Squeeze out as much air as possible and seal the bag. Massage the bag a few times so the chicken pieces are covered evenly with the sauce. Transfer to the fridge and marinate overnight (highly recommended), or for at least 4 hours.',
   'When the chicken is marinated and the glaze is chilled, you’re ready to cook.',
   'Preheat the oven to 375°F (190°C). Line a large baking tray with aluminum foil. Place the chicken onto the tray without overlapping. Bake for 30 minutes.',
   'Turn on the broiler. Baste the top side of the chicken. Broil for 2 to 3 minutes. Baste again. Broil for another 2 to 3 minutes. The chicken should look glossy, lightly charred, and cooked through. You can test the doneness by inserting a thermometer into the thickest part of the chicken. It should read 165°F (74°C).',
   'Once done, cover loosely with aluminum foil. Let rest for 10 minutes before serving. Serve the chicken hot over rice as a main dish.'],
  'Nutrition_Facts': ['Serving: 1serving',
   'Calories: 283kcal',
   'Carbohydrates: 12.8g',
   'Protein: 23.6g',
   'Fat: 14.9g',
   'Saturated Fat: 4.2g',
   'Cholesterol: 84mg',
   'Sodium: 229mg',
   'Potassium: 196mg',
   'Fiber: 0.3g',
   'Sugar: 9.5g',
   'Calcium: 17mg',
   'Iron: 2mg']}]

In [14]:
def scrape_page(page_num: int):

  response = session.get("https://omnivorescookbook.com/category/recipe/?_paged={}".format(page_num), timeout=10)
  response.raise_for_status()

  data = []

  soup = BeautifulSoup(response.text, "html.parser")

  recipes = soup.find_all(class_ = "gridtitle")


  for recipe in recipes:

    data.append(scrape_recipe(recipe.a.get("href")))

  return data

In [15]:
columns = [
      "Name",
      "Ingredients_List",
      "Ingredients_Names",
      "Procedure",
      "Nutrition_Facts"
  ]

temp_out = []

for page_num in range(1, 3):
  data = scrape_page(page_num)
  temp_out.extend(data)
#print(out)
df = pd.DataFrame(temp_out, columns=columns)

print(f"Total recipes scraped: {len(df)}")

display(df.head())

Total recipes scraped: 80

,Name,Ingredients_List,Ingredients_Names,Procedure,Nutrition_Facts
0,thai-fish-cakes,"[1 pound white fish fillet , cut into 1-inch (...","[white fish fillet, red curry paste, large egg...","[Fish cake:, Combine the fish, curry paste, eg...","[Serving: 1of the 6 servings, Calories: 308kca..."
1,budae-jjigae,"[1 tablespoon peanut oil (or vegetable oil), 1...","[peanut oil, ground beef, green onions, garlic...",[Heat oil in a 4-quart dutch oven (or heavy po...,"[Serving: 4servings, Calories: 522kcal, Carboh..."
2,drunken-chicken,[2 bone-in skin-on chicken leg quarters (inclu...,"[bone-in skin-on chicken leg quarters, salt, g...",[Combine the salt and Sichuan peppercorns in a...,"[Serving: 1serving, Calories: 99kcal, Carbohyd..."
3,matcha-tiramisu,[2 tablespoons ceremonial grade matcha and ext...,"[ceremonial grade matcha, very hot water, masc...",[To make the matcha soak: Sift matcha into a m...,"[Serving: 1serving, Calories: 224kcal, Carbohy..."
4,clams-in-black-bean-sauce,"[2 lbs manila clams, Salt , for soaking the cl...","[manila clams, Salt, vegetable oil, Shaoxing W...",[Place the clams in a large bowl. Add 8 cups c...,"[Serving: 1serving, Calories: 318kcal, Carbohy..."

#Scrape the entire site!

In [16]:
pages = 18

out = []

for page_num in range(1, pages + 1):



    try:
      data = scrape_page(page_num)
      out.extend(data)

    except Exception as e:

      print(f"Error on page {page_num}: {e}")
      break
    print(f"page number: {page_num}")
    time.sleep(4) #be nice to the site, too aggresive can cause an exception

page number: 1
page number: 2
page number: 3
page number: 4
page number: 5
page number: 6
page number: 7
page number: 8
page number: 9
page number: 10
page number: 11
page number: 12
page number: 13
page number: 14
page number: 15
page number: 16
page number: 17
page number: 18

#Store Data in Pandas df
We can then get some insights and then export to CSV file

In [17]:
columns = [
      "Name",
      "Ingredients_List",
      "Ingredients_Names",
      "Procedure",
      "Nutrition_Facts"
  ]

df = pd.DataFrame(out, columns=columns)

print(f"Total recipes scraped: {len(df)}")

display(df.head())

Total recipes scraped: 688

,Name,Ingredients_List,Ingredients_Names,Procedure,Nutrition_Facts
0,thai-fish-cakes,"[1 pound white fish fillet , cut into 1-inch (...","[white fish fillet, red curry paste, large egg...","[Fish cake:, Combine the fish, curry paste, eg...","[Serving: 1of the 6 servings, Calories: 308kca..."
1,budae-jjigae,"[1 tablespoon peanut oil (or vegetable oil), 1...","[peanut oil, ground beef, green onions, garlic...",[Heat oil in a 4-quart dutch oven (or heavy po...,"[Serving: 4servings, Calories: 522kcal, Carboh..."
2,drunken-chicken,[2 bone-in skin-on chicken leg quarters (inclu...,"[bone-in skin-on chicken leg quarters, salt, g...",[Combine the salt and Sichuan peppercorns in a...,"[Serving: 1serving, Calories: 99kcal, Carbohyd..."
3,matcha-tiramisu,[2 tablespoons ceremonial grade matcha and ext...,"[ceremonial grade matcha, very hot water, masc...",[To make the matcha soak: Sift matcha into a m...,"[Serving: 1serving, Calories: 224kcal, Carbohy..."
4,clams-in-black-bean-sauce,"[2 lbs manila clams, Salt , for soaking the cl...","[manila clams, Salt, vegetable oil, Shaoxing W...",[Place the clams in a large bowl. Add 8 cups c...,"[Serving: 1serving, Calories: 318kcal, Carbohy..."

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 688 entries, 0 to 687
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               688 non-null    object
 1   Ingredients_List   688 non-null    object
 2   Ingredients_Names  688 non-null    object
 3   Procedure          688 non-null    object
 4   Nutrition_Facts    688 non-null    object
dtypes: object(5)
memory usage: 27.0+ KB

In [19]:
df = df.loc[df.astype(str).drop_duplicates().index]
df

,Name,Ingredients_List,Ingredients_Names,Procedure,Nutrition_Facts
0,thai-fish-cakes,"[1 pound white fish fillet , cut into 1-inch (...","[white fish fillet, red curry paste, large egg...","[Fish cake:, Combine the fish, curry paste, eg...","[Serving: 1of the 6 servings, Calories: 308kca..."
1,budae-jjigae,"[1 tablespoon peanut oil (or vegetable oil), 1...","[peanut oil, ground beef, green onions, garlic...",[Heat oil in a 4-quart dutch oven (or heavy po...,"[Serving: 4servings, Calories: 522kcal, Carboh..."
2,drunken-chicken,[2 bone-in skin-on chicken leg quarters (inclu...,"[bone-in skin-on chicken leg quarters, salt, g...",[Combine the salt and Sichuan peppercorns in a...,"[Serving: 1serving, Calories: 99kcal, Carbohyd..."
3,matcha-tiramisu,[2 tablespoons ceremonial grade matcha and ext...,"[ceremonial grade matcha, very hot water, masc...",[To make the matcha soak: Sift matcha into a m...,"[Serving: 1serving, Calories: 224kcal, Carbohy..."
4,clams-in-black-bean-sauce,"[2 lbs manila clams, Salt , for soaking the cl...","[manila clams, Salt, vegetable oil, Shaoxing W...",[Place the clams in a large bowl. Add 8 cups c...,"[Serving: 1serving, Calories: 318kcal, Carbohy..."
...,...,...,...,...,...
683,spinach-salad,"[6 tablespoons olive oil, 2 tablespoons rice v...","[olive oil, rice vinegar, shallot, honey, toas...",[Wash spinach thoroughly with running water. R...,[]
684,baked-costa-rican-style-fish-with-black-beans-...,"[300 g fish fillet tilapia, bass, or catfish, ...","[fish fillet, freshly squeezed orange juice, f...",[Add fish and all the ingredients for marinate...,[]
685,creamy-chicken-potato-salad,"[1 lb (450 g) red potatoes (*Footnote 1), 1 ta...","[red potatoes, plus 1/2 teaspoon salt, boneles...",[Prepare a steamer by adding water to the pot....,"[Serving: 1serving, Calories: 295kcal, Carbohy..."
686,pork-stock,"[1.4 kg (3 pounds) pork leg bones, 1 thumbnail...","[pork leg bones, thumbnail ginger, large onion]",[Put pork bones in a large pot and add water u...,[]
687,chashu-braised-pork-belly,"[500 grams pork belly rind removed, cut into 2...","[pork belly, salt, vegetable oil, thumb ginger...",[Rub the pork belly with salt. Heat oil in a n...,[]

#Save Data to CSV

In [20]:
output_file = "omnivores_cookbook_recipes.csv"

df.to_csv(
    output_file,
    index=False,
    encoding="utf-8"
)

print(f"Output file: {output_file}")

Output file: omnivores_cookbook_recipes.csv