<a href="https://colab.research.google.com/github/warrensuca/chinese-recipe-api/blob/main/the_woks_of_life_scraper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#The Woks of Life Recipe Scraper
This notebook scrapes recipe data from the Woks of Life website: https://thewoksoflife.com/category/recipes/:

For each recipe, we collect:

- Name
- Ingredients Full List
- Ingredients Names List
  - Used in clustering, very difficult to parse from full list
- Procedure
- Nutrition Facts

The final dataset is stored as a Pandas DataFrame and exported to CSV.

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from IPython.display import display
import time
print("setup complete")

setup complete

In [7]:
session = requests.Session()

session.headers.update({
    "User-Agent":
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
})

print("Session initialized")

Session initialized

#Scrape individual recipe URL
Exploration. Later, we will turn this into a function

In [30]:

url = "https://thewoksoflife.com/ayam-kecap-indonesian-braised-chicken/"
headings = [
      "Name",
      "Ingredients_List",
      "Ingredients_Names",
      "Procedure",
      "Nutrition_Facts"
  ]

response = session.get(url, timeout=10)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")

recipe_data = {
    "Name": url.split("/")[-2] #getting title is an additional call, just clean later
}
print(recipe_data["Name"])
print('\n')

ingredients_list_raw = soup.find_all("li", class_ = "wprm-recipe-ingredient")
ingredients_list = []

for ingredient in ingredients_list_raw:
  ingredients_list.append(ingredient.get_text()[2:]) #remove a bullet point svg

print(ingredients_list)
print('\n')
recipe_data["Ingredients_List"] = ingredients_list

ingredients_names_raw = soup.find_all("span", class_ = "wprm-recipe-ingredient-name")
ingredients_names = []

for ingredient_name in ingredients_names_raw:
  ingredients_names.append(ingredient_name.get_text())

print(ingredients_names)
print('\n')
recipe_data["Ingredients_Names"] = ingredients_names

procedure_list_raw = soup.find_all("li", class_ = "wprm-recipe-instruction")
procedure_list = []

for procedure in procedure_list_raw:
  procedure_list.append(procedure.get_text())

print(procedure_list)
print('\n')
recipe_data["Procedure"] = procedure_list

nutrition_facts_list_raw = soup.find_all("span", class_ = "wprm-nutrition-label-text-nutrition-container")
nutrition_facts = []

servings = soup.find("span", class_ = "wprm-recipe-servings-adjustable-tooltip").get_text()
if(servings):
  nutrition_facts.append(servings)

for nutrition_fact in nutrition_facts_list_raw:
  #print(nutrition_fact.get_text())
  nutrition_facts.append(nutrition_fact.get_text())

print(nutrition_facts)

recipe_data["Nutrition_Facts"] = nutrition_facts

ayam-kecap-indonesian-braised-chicken


['2½ pounds chicken drumsticks', '½ teaspoon salt', '2 tablespoons neutral oil (such as canola, vegetable, or avocado oil)', '½ teaspoon ginger (finely minced or grated)', '3 cloves garlic (chopped)', '1/3 cup shallot or red onion (finely diced)', '3 dried chili peppers (optional)', '2¼ cups low sodium chicken stock', '¾ teaspoon galangal (or sand ginger powder)', '¾ teaspoon coriander powder', '¾ teaspoon ground or whole cloves', '3 dried Makrut lime leaves', '3 tablespoons kecap manis (Indonesian sweet soy sauce)', '2 tablespoons soy sauce', '1 teaspoon tamarind paste (optional)', '½ teaspoon ground white or black pepper']


['chicken drumsticks', 'salt', 'neutral oil', 'ginger', 'garlic', 'shallot or red onion', 'dried chili peppers', 'low sodium chicken stock', 'galangal', 'coriander powder', 'ground or whole cloves', 'dried Makrut lime leaves', 'kecap manis', 'soy sauce', 'tamarind paste', 'ground white or black pepper']


['In a large bowl, add the chicken legs, and sprinkle them with the salt. Rub the salt in evenly, and let sit for at least 10 minutes. Heat a medium pot over medium-high heat, and add the oil. Sear the chicken legs until lightly browned on all sides. Remove the chicken to a plate.', 'Add the ginger, garlic, shallot/onion, and dried red chili peppers (if using). Cook until caramelized and fragrant.', 'Next, add the chicken stock and stir to deglaze the bottom of the pot. Add galangal powder, coriander powder, cloves, lime leaves, kecap manis, soy sauce, tamarind paste (if using) and the pepper. Stir to combine.', 'Bring the mixture to a simmer, and add the seared chicken and any juices back to the pot. Cook uncovered for 25 minutes, turning the chicken every 5 to 10 minutes for even cooking. Skim off any foam that may emerge at the surface.', 'Turn the heat up slightly and continue to cook off the liquid until the sauce thickens enough to coat a spoon. Taste for seasoning and add additional salt only if needed. Serve with rice and a stir-fried vegetable on the side.']


['6', 'Calories: 313kcal (16%)', 'Carbohydrates: 14g (5%)', 'Protein: 25g (50%)', 'Fat: 17g (26%)', 'Saturated Fat: 4g (20%)', 'Polyunsaturated Fat: 4g', 'Monounsaturated Fat: 8g', 'Trans Fat: 0.1g', 'Cholesterol: 116mg (39%)', 'Sodium: 709mg (30%)', 'Potassium: 448mg (13%)', 'Fiber: 1g (4%)', 'Sugar: 8g (9%)', 'Vitamin A: 127IU (3%)', 'Vitamin C: 2mg (2%)', 'Calcium: 31mg (3%)', 'Iron: 1mg (6%)']

#Create function based off exploration
This function will be used on each recipe of the site

In [36]:
def scrape_recipe(url: str):


  response = session.get(url, timeout=10)
  response.raise_for_status()

  soup = BeautifulSoup(response.text, "html.parser")

  recipe_data = {
      "Name": url.split("/")[-2] #getting title is an additional call, just clean later
  }


  ingredients_list_raw = soup.find_all("li", class_ = "wprm-recipe-ingredient")
  ingredients_list = []

  for ingredient in ingredients_list_raw:
    ingredients_list.append(ingredient.get_text()[2:]) #remove a bullet point svg


  recipe_data["Ingredients_List"] = ingredients_list


  ingredients_names_raw = soup.find_all("span", class_ = "wprm-recipe-ingredient-name")
  ingredients_names = []

  for ingredient_name in ingredients_names_raw:
    ingredients_names.append(ingredient_name.get_text())

  recipe_data["Ingredients_Names"] = ingredients_names


  procedure_list_raw = soup.find_all("li", class_ = "wprm-recipe-instruction")
  procedure_list = []

  for procedure in procedure_list_raw:
    procedure_list.append(procedure.get_text())



  recipe_data["Procedure"] = procedure_list

  nutrition_facts_list_raw = soup.find_all("span", class_ = "wprm-nutrition-label-text-nutrition-container")
  nutrition_facts = []

  servings_raw = soup.find("span", class_ = "wprm-recipe-servings-adjustable-tooltip")
  if servings_raw is not None:
    nutrition_facts.append(servings_raw.get_text())

  for nutrition_fact in nutrition_facts_list_raw:
    #print(nutrition_fact.get_text())
    nutrition_facts.append(nutrition_fact.get_text())

  recipe_data["Nutrition_Facts"] = nutrition_facts

  return recipe_data

In [24]:
recipe_data = scrape_recipe("https://thewoksoflife.com/pork-belly-char-siu/")

recipe_data

{'Name': 'pork-belly-char-siu',
 'Ingredients_List': ['2 pounds boneless skinless pork belly (if trimming your pork belly at home, save the bones and skins for soup!)',
  '3 tablespoons granulated sugar',
  '1½ teaspoons salt',
  '¼ teaspoon white pepper',
  '¼ teaspoon five spice powder',
  '1 tablespoon hoisin sauce',
  '1 tablespoon Shaoxing wine',
  '2 teaspoons light soy sauce',
  '½ teaspoon sesame oil',
  '1 clove garlic (minced)',
  '4 to 5 drops of red food coloring (optional)',
  '1 tablespoon maltose or honey',
  '1 tablespoon hot water'],
 'Ingredients_Names': ['boneless skinless pork belly',
  'granulated sugar',
  'salt',
  'white pepper',
  'five spice powder',
  'hoisin sauce',
  'Shaoxing wine',
  'light soy sauce',
  'sesame oil',
  'garlic',
  'drops of red food coloring',
  'maltose or honey',
  'hot water'],
 'Procedure': ['If you have a larger piece of pork belly, cut it lengthwise into long 1½- to 2-inch (4-5cm) thick strips.',
  'Make the marinade in a large bowl by combining the sugar, salt, white pepper, five spice powder, hoisin sauce, Shaoxing wine, light soy sauce, sesame oil, and minced garlic. Add the pork belly, and use your hands to work the marinade into the strips. Cover and marinate in the refrigerator overnight.',
  'Arrange a rack in the middle of the oven and preheat to 400°F/205°C. Prepare a sheet pan with heavy duty aluminum foil and a flat wire rack. Lay the pork belly strips on the rack, and add just enough water to thinly cover the bottom of the sheet pan (about 1-1½ cups/250-350ml). Set aside the leftover marinade in the bowl.',
  'Roast for 40 minutes. While that’s happening, mix the maltose with hot water in a small bowl to dissolve. Mix in the remaining marinade. You’ll use this mixture for basting.',
  'After the first 40 minutes, baste the pork belly pieces with a brush, flip and baste the other side. Return to the oven for 20 minutes. Baste again generously, turn over to baste the other side and return to the oven for another 10 minutes.',
  'If desired, you can baste one more time, and broil the pork belly for a few minutes to crisp up the surface. Remove from the oven and rest for 10 minutes on the counter.',
  'To serve, slice the pork belly into ½- to ¾-inch thick (1-2cm) pieces, and enjoy with steamed rice and a side of green vegetables!'],
 'Nutrition_Facts': ['6',
  'Calories: 682kcal (34%)',
  'Carbohydrates: 11g (4%)',
  'Protein: 15g (30%)',
  'Fat: 81g (125%)',
  'Saturated Fat: 29g (145%)',
  'Polyunsaturated Fat: 9g',
  'Monounsaturated Fat: 38g',
  'Cholesterol: 109mg (36%)',
  'Sodium: 785mg (33%)',
  'Potassium: 294mg (8%)',
  'Fiber: 0.2g (1%)',
  'Sugar: 10g (11%)',
  'Vitamin A: 16IU',
  'Vitamin C: 1mg (1%)',
  'Calcium: 12mg (1%)',
  'Iron: 1mg (6%)']}

#Scrape single page
Exploration

In [25]:

response = session.get("https://thewoksoflife.com/category/recipes/page/{}/".format(1), timeout=10)
response.raise_for_status()

data = []

soup = BeautifulSoup(response.text, "html.parser")

recipes = soup.find_all(class_ = "wp-block-post-featured-image")


for recipe in recipes[:5]:

  data.append(scrape_recipe(recipe.a.get("href")))
data

[{'Name': 'shallot-vinaigrette',
  'Ingredients_List': ['1  large shallot (minced)',
   '2 tablespoons hot water',
   '¼ cup white wine vinegar',
   '2 tablespoons finely chopped chives',
   '1 garlic clove (minced)',
   '½ cup extra virgin olive oil',
   '2 teaspoons dijon mustard',
   '2 teaspoons honey',
   '1 teaspoon sea salt  or kosher salt',
   '¼ teaspoon freshly ground black pepper'],
  'Ingredients_Names': ['large shallot',
   'hot water',
   'white wine vinegar',
   'finely chopped chives',
   'garlic clove',
   'extra virgin olive oil',
   'dijon mustard',
   'honey',
   'sea salt',
   'freshly ground black pepper'],
  'Procedure': ['In a measuring cup, add the shallots and hot water. Then stir in the white wine vinegar, and let it sit while you prep the chives and garlic.',
   'To the measuring cup, add the olive oil, dijon mustard, honey, salt, pepper, and garlic. Whisk everything together until it’s emulsified. Add the chives, and whisk again. Give it a taste, and adjust seasoning to taste.'],
  'Nutrition_Facts': ['6',
   'Calories: 173kcal (9%)',
   'Carbohydrates: 3g (1%)',
   'Protein: 0.3g (1%)',
   'Fat: 18g (28%)',
   'Saturated Fat: 2g (10%)',
   'Polyunsaturated Fat: 2g',
   'Monounsaturated Fat: 13g',
   'Sodium: 408mg (17%)',
   'Potassium: 28mg (1%)',
   'Fiber: 0.3g (1%)',
   'Sugar: 2g (2%)',
   'Vitamin A: 45IU (1%)',
   'Vitamin C: 1mg (1%)',
   'Calcium: 6mg (1%)',
   'Iron: 0.3mg (2%)']},
 {'Name': 'sesame-tofu',
  'Ingredients_List': ['2 blocks firm or extra firm tofu (anywhere from 14-16 oz./400-450g per package is fine, as tofu blocks vary)',
   '2/3 cup cornstarch',
   '1/4 cup un-toasted sesame seeds',
   '¾ teaspoon fine sea salt',
   '½ teaspoon white pepper',
   '½ teaspoon garlic powder',
   '½ teaspoon onion powder',
   '¼ cup neutral oil (such as vegetable, canola, or avocado oil)',
   '2 garlic cloves (minced)',
   '¾ cup water (low-sodium vegetable stock, or low-sodium chicken stock)',
   '3 tablespoons sugar (brown sugar also works)',
   '1½ tablespoons vegetarian oyster sauce (or regular oyster sauce)',
   '1 tablespoon light soy sauce',
   '1 tablespoon honey',
   '1 tablespoon Shaoxing wine (or clear rice wine)',
   '1½ teaspoons rice vinegar',
   '1½ teaspoons sesame oil',
   '⅛ teaspoon white pepper',
   '2 teaspoons cornstarch',
   '1 tablespoon water',
   '1 teaspoon toasted sesame seeds',
   '½ scallion (green parts only, thinly sliced)'],
  'Ingredients_Names': ['firm or extra firm tofu',
   'cornstarch',
   'un-toasted sesame seeds',
   'fine sea salt',
   'white pepper',
   'garlic powder',
   'onion powder',
   'neutral oil',
   'garlic cloves',
   'water',
   'sugar',
   'vegetarian oyster sauce',
   'light soy sauce',
   'honey',
   'Shaoxing wine',
   'rice vinegar',
   'sesame oil',
   'white pepper',
   'cornstarch',
   'water',
   'toasted sesame seeds',
   'scallion'],
  'Procedure': ['Drain each block of tofu. Using your hands, gently squeeze the block to release water. You can also pat it dry on a clean dishcloth. Cut each block into 1-inch (3cm) cubes.',
   'In a shallow bowl, combine the cornstarch, sesame seeds, sea salt, white pepper, garlic powder, and onion powder. Working in 2 batches, dredge the tofu cubes in the cornstarch mixture. It doesn’t have to be perfect, but do your best to cover all sides and press the mixture into the tofu cubes evenly.',
   'Heat a large nonstick pan or cast-iron skillet over medium-high heat. Add the neutral oil. When the oil is shimmering, add half the tofu cubes. Fry for 4 to 5 minutes per side, until golden brown and crispy. As they get golden, you can flip them a few times to get all the sides crispy. Again, it doesn’t have to be perfect, and it’s easier than it sounds. Transfer the tofu to a plate, and repeat with the second batch. Remove all the tofu to a plate.',
   'In the same skillet, make the sauce. Add the minced garlic and cook for 1 minute. Add the water/stock, sugar, vegetarian oyster sauce, light soy sauce, honey, Shaoxing wine, rice vinegar, sesame oil, and white pepper. Bring to a simmer, and simmer for 3 minutes.',
   'Combine the cornstarch and water into a slurry. Add it to the sauce, and let it thicken and cook for another minute. Toss the tofu in the sauce. Serve, sprinkled with sesame seeds and scallions.'],
  'Nutrition_Facts': ['6',
   'Calories: 358kcal (18%)',
   'Carbohydrates: 29g (10%)',
   'Protein: 15g (30%)',
   'Fat: 20g (31%)',
   'Saturated Fat: 2g (10%)',
   'Polyunsaturated Fat: 9g',
   'Monounsaturated Fat: 9g',
   'Trans Fat: 0.04g',
   'Sodium: 592mg (25%)',
   'Potassium: 54mg (2%)',
   'Fiber: 2g (8%)',
   'Sugar: 9g (10%)',
   'Vitamin A: 11IU',
   'Vitamin C: 1mg (1%)',
   'Calcium: 261mg (26%)',
   'Iron: 3mg (17%)']},
 {'Name': 'pork-belly-char-siu',
  'Ingredients_List': ['2 pounds boneless skinless pork belly (if trimming your pork belly at home, save the bones and skins for soup!)',
   '3 tablespoons granulated sugar',
   '1½ teaspoons salt',
   '¼ teaspoon white pepper',
   '¼ teaspoon five spice powder',
   '1 tablespoon hoisin sauce',
   '1 tablespoon Shaoxing wine',
   '2 teaspoons light soy sauce',
   '½ teaspoon sesame oil',
   '1 clove garlic (minced)',
   '4 to 5 drops of red food coloring (optional)',
   '1 tablespoon maltose or honey',
   '1 tablespoon hot water'],
  'Ingredients_Names': ['boneless skinless pork belly',
   'granulated sugar',
   'salt',
   'white pepper',
   'five spice powder',
   'hoisin sauce',
   'Shaoxing wine',
   'light soy sauce',
   'sesame oil',
   'garlic',
   'drops of red food coloring',
   'maltose or honey',
   'hot water'],
  'Procedure': ['If you have a larger piece of pork belly, cut it lengthwise into long 1½- to 2-inch (4-5cm) thick strips.',
   'Make the marinade in a large bowl by combining the sugar, salt, white pepper, five spice powder, hoisin sauce, Shaoxing wine, light soy sauce, sesame oil, and minced garlic. Add the pork belly, and use your hands to work the marinade into the strips. Cover and marinate in the refrigerator overnight.',
   'Arrange a rack in the middle of the oven and preheat to 400°F/205°C. Prepare a sheet pan with heavy duty aluminum foil and a flat wire rack. Lay the pork belly strips on the rack, and add just enough water to thinly cover the bottom of the sheet pan (about 1-1½ cups/250-350ml). Set aside the leftover marinade in the bowl.',
   'Roast for 40 minutes. While that’s happening, mix the maltose with hot water in a small bowl to dissolve. Mix in the remaining marinade. You’ll use this mixture for basting.',
   'After the first 40 minutes, baste the pork belly pieces with a brush, flip and baste the other side. Return to the oven for 20 minutes. Baste again generously, turn over to baste the other side and return to the oven for another 10 minutes.',
   'If desired, you can baste one more time, and broil the pork belly for a few minutes to crisp up the surface. Remove from the oven and rest for 10 minutes on the counter.',
   'To serve, slice the pork belly into ½- to ¾-inch thick (1-2cm) pieces, and enjoy with steamed rice and a side of green vegetables!'],
  'Nutrition_Facts': ['6',
   'Calories: 682kcal (34%)',
   'Carbohydrates: 11g (4%)',
   'Protein: 15g (30%)',
   'Fat: 81g (125%)',
   'Saturated Fat: 29g (145%)',
   'Polyunsaturated Fat: 9g',
   'Monounsaturated Fat: 38g',
   'Cholesterol: 109mg (36%)',
   'Sodium: 785mg (33%)',
   'Potassium: 294mg (8%)',
   'Fiber: 0.2g (1%)',
   'Sugar: 10g (11%)',
   'Vitamin A: 16IU',
   'Vitamin C: 1mg (1%)',
   'Calcium: 12mg (1%)',
   'Iron: 1mg (6%)']},
 {'Name': 'red-bean-zongzi',
  'Ingredients_List': ['2 pounds sweet rice (also known as sticky rice or glutinous rice; about 4 1/2 cups)',
   '3 tablespoons lye water (potassium carbonate solution)',
   '1 tablespoon neutral oil (such as vegetable, canola, or avocado oil)',
   '1 cup dried red adzuki beans',
   '26 dried bamboo or reed leaves (2 per zongzi, with a couple extra in case of tearing)',
   'Sugar, maple syrup, or honey (to serve with the zongzi)'],
  'Ingredients_Names': ['sweet rice',
   'lye water',
   'neutral oil',
   'dried red adzuki beans',
   'dried bamboo or reed leaves',
   'Sugar, maple syrup, or honey'],
  'Procedure': ['In a large, fine mesh strainer, rinse the sweet rice, agitating it with your hands until the water runs clear. You can also do this in a large bowl, changing the water out a few times. The rice will expand about 20-30%, so make sure your bowl is large enough. Transfer the rice to a large bowl with enough water so that the water line is ½-inch above the rice. Stir in the lye water and oil. Once the lye water hits the fresh water, both the rice and water will turn a light yellow color. Cover and soak in the refrigerator overnight.',
   'In a large basin (or your kitchen sink), soak the bamboo leaves overnight. Weigh the leaves down with something heavy to make sure all the leaves are submerged.',
   'Rinse and soak the red beans in a bowl of water overnight.',
   'Clean each bamboo leaf, front and back, with a clean kitchen towel, shaking off any excess water and trimming off about a half inch of the leaf at the base (this part is too tough to fold). Set aside.',
   'Take the soaked rice out of the refrigerator, and drain off all of the liquid. Drain the soaked red beans, and combine with the rice. Mix well.',
   'Take two bamboo leaves and follow the steps shown in the photos to wrap them. Start by layering the two leaves together so they’re overlapping, and folding up the bottom to create a cone. Fill with the rice/bean mixture. (Each dumpling will take about ¾ – 1 cup of the mixture.) Fold the two sides into the middle lengthwise, cupping your hands at the bottom of the cone so it doesn’t fall apart. Pinch the leaves at the top to start closing them around the rice, and fold down over the rice. Tie the bundle securely with kitchen string, not tying too tightly so the rice has room to expand during cooking.',
   'To cook in an Instant Pot: Neatly nest the zongzi in the Instant Pot, minimizing gaps. Fill the pot until it’s no more than 2 inches below the max fill line. Put the metal steamer rack that came with your pot on top of the zongzi, to keep them in place during cooking. Fill with water just until you reach the max fill line. (If you have fewer zongzi, simply cover with at least 2 inches of water.) Cover the Instant Pot and lock the lid in place. Set on manual high pressure for 1 hour, and allow the pressure to release naturally. Be sure all pressure is released before safely opening the lid.',
   'To cook on the stove: If you don’t have an Instant Pot, arrange the zongzi neatly in a stockpot, and fill with water about one inch above the top of the zongzi. Add 1½ teaspoons of lye water to the pot, and place a heat-proof dish on top of everything to weigh down the zongzi. Bring the water to a boil, and then reduce the heat to medium. Cook, covered, for 2½ to 3 hours. Check the water levels periodically, replenishing the pot with boiling water when the water line falls below the top of zongzi. Turn off the heat. Do not touch the pot, and let the contents cool gradually until they zongzi are just shy of room temperature but still warm. This step allows them to continue cooking in the residual heat.',
   'Serve the zongzi warm or at room temperature with sugar, maple syrup, or honey!'],
  'Nutrition_Facts': ['12',
   'Calories: 344kcal (17%)',
   'Carbohydrates: 72g (24%)',
   'Protein: 8g (16%)',
   'Fat: 2g (3%)',
   'Saturated Fat: 0.2g (1%)',
   'Polyunsaturated Fat: 0.5g',
   'Monounsaturated Fat: 1g',
   'Trans Fat: 0.01g',
   'Sodium: 6mg',
   'Potassium: 264mg (8%)',
   'Fiber: 4g (16%)',
   'Vitamin A: 3IU',
   'Calcium: 19mg (2%)',
   'Iron: 2mg (11%)']},
 {'Name': 'stir-fry-spinach',
  'Ingredients_List': ['1 pound spinach (preferably Taiwanese spinach)',
   '3 tablespoons neutral oil (such as canola, vegetable, or avocado oil)',
   '2-3 cloves garlic (minced)',
   'Salt to taste',
   '¼ teaspoon white pepper',
   '1 teaspoon sesame oil'],
  'Ingredients_Names': ['spinach',
   'neutral oil',
   'garlic',
   'Salt to taste',
   'white pepper',
   'sesame oil'],
  'Procedure': ['Wash spinach clean by soaking a few times and agitating it in the water to loosen any sand or debris. Each time you soak the spinach, lift it out of the water into a colander rather than pouring it, so the dirt and sand stays at the bottom of the bowl.',
   'Shake the excess water off your washed spinach or run it through a salad spinner. Cut the spinach into 3-4 inch pieces, keeping the root end of the stems separate from the leaves and tender parts of the stem. Don’t trim away the root unless it feels very woody.',
   'Heat your carbon steel wok or skillet over medium high until it’s just lightly smoking (this doesn’t apply to nonstick pans). Add the oil, followed by the garlic and the root portions of the spinach, which take a bit longer to cook. Increase the heat to high, cook for a minute, then add the rest of the spinach.',
   'Stir-fry everything well, letting the spinach wilt. Add the salt, white pepper, and sesame oil. Stir-fry until the spinach is completely wilted but still bright green. Transfer to a dish and serve.'],
  'Nutrition_Facts': ['4',
   'Calories: 130kcal (7%)',
   'Carbohydrates: 5g (2%)',
   'Protein: 3g (6%)',
   'Fat: 12g (18%)',
   'Saturated Fat: 1g (5%)',
   'Polyunsaturated Fat: 4g',
   'Monounsaturated Fat: 7g',
   'Trans Fat: 0.04g',
   'Sodium: 235mg (10%)',
   'Potassium: 639mg (18%)',
   'Fiber: 3g (12%)',
   'Sugar: 0.5g (1%)',
   'Vitamin A: 10633IU (213%)',
   'Vitamin C: 32mg (39%)',
   'Calcium: 115mg (12%)',
   'Iron: 3mg (17%)']}]

In [26]:
def scrape_page(page_num: int):

  response = session.get("https://thewoksoflife.com/category/recipes/page/{}/".format(page_num), timeout=10)
  response.raise_for_status()

  data = []

  soup = BeautifulSoup(response.text, "html.parser")

  recipes = soup.find_all(class_ = "wp-block-post-featured-image")


  for recipe in recipes:

    data.append(scrape_recipe(recipe.a.get("href")))

  return data

In [37]:
columns = [
      "Name",
      "Ingredients_List",
      "Ingredients_Names",
      "Procedure",
      "Nutrition_Facts"
  ]

temp_out = []

for page_num in range(1, 3):

  data = scrape_page(page_num)
  temp_out.extend(data)
#print(out)
df = pd.DataFrame(temp_out, columns=columns)

print(f"Total recipes scraped: {len(df)}")

display(df.head())

Total recipes scraped: 36

,Name,Ingredients_List,Ingredients_Names,Procedure,Nutrition_Facts
0,shallot-vinaigrette,"[1 large shallot (minced), 2 tablespoons hot ...","[large shallot, hot water, white wine vinegar,...","[In a measuring cup, add the shallots and hot ...","[6, Calories: 173kcal (9%), Carbohydrates: 3g ..."
1,sesame-tofu,[2 blocks firm or extra firm tofu (anywhere fr...,"[firm or extra firm tofu, cornstarch, un-toast...","[Drain each block of tofu. Using your hands, g...","[6, Calories: 358kcal (18%), Carbohydrates: 29..."
2,pork-belly-char-siu,[2 pounds boneless skinless pork belly (if tri...,"[boneless skinless pork belly, granulated suga...","[If you have a larger piece of pork belly, cut...","[6, Calories: 682kcal (34%), Carbohydrates: 11..."
3,red-bean-zongzi,[2 pounds sweet rice (also known as sticky ric...,"[sweet rice, lye water, neutral oil, dried red...","[In a large, fine mesh strainer, rinse the swe...","[12, Calories: 344kcal (17%), Carbohydrates: 7..."
4,stir-fry-spinach,[1 pound spinach (preferably Taiwanese spinach...,"[spinach, neutral oil, garlic, Salt to taste, ...",[Wash spinach clean by soaking a few times and...,"[4, Calories: 130kcal (7%), Carbohydrates: 5g ..."

#Scrape the entire site!

In [38]:
pages = 80

out = []

for page_num in range(1, pages + 1):



    try:
      data = scrape_page(page_num)
      out.extend(data)

    except Exception as e:

      print(f"Error on page {page_num}: {e}")
      break
    print(f"page number: {page_num}")
    time.sleep(4) #be nice to the site, too aggresive can cause an exception

page number: 1
page number: 2
page number: 3
page number: 4
page number: 5
page number: 6
page number: 7
page number: 8
page number: 9
page number: 10
page number: 11
page number: 12
page number: 13
page number: 14
page number: 15
page number: 16
page number: 17
page number: 18
page number: 19
page number: 20
page number: 21
page number: 22
page number: 23
page number: 24
page number: 25
page number: 26
page number: 27
page number: 28
page number: 29
page number: 30
page number: 31
page number: 32
page number: 33
page number: 34
page number: 35
page number: 36
page number: 37
page number: 38
page number: 39
page number: 40
page number: 41
page number: 42
page number: 43
page number: 44
page number: 45
page number: 46
page number: 47
page number: 48
page number: 49
page number: 50
page number: 51
page number: 52
page number: 53
page number: 54
page number: 55
page number: 56
page number: 57
page number: 58
page number: 59
page number: 60
page number: 61
page number: 62
page number: 63
page number: 64
page number: 65
page number: 66
page number: 67
page number: 68
page number: 69
page number: 70
page number: 71
page number: 72
page number: 73
page number: 74
page number: 75
page number: 76
page number: 77
page number: 78
page number: 79
Error on page 80: 404 Client Error: Not Found for url: https://thewoksoflife.com/category/recipes/page/80/

#Store Data in Pandas df
We can then get some insights and then export to CSV file

In [39]:
columns = [
      "Name",
      "Ingredients_List",
      "Ingredients_Names",
      "Procedure",
      "Nutrition_Facts"
  ]

df = pd.DataFrame(out, columns=columns)

print(f"Total recipes scraped: {len(df)}")

display(df.head())

Total recipes scraped: 1414

,Name,Ingredients_List,Ingredients_Names,Procedure,Nutrition_Facts
0,shallot-vinaigrette,"[1 large shallot (minced), 2 tablespoons hot ...","[large shallot, hot water, white wine vinegar,...","[In a measuring cup, add the shallots and hot ...","[6, Calories: 173kcal (9%), Carbohydrates: 3g ..."
1,sesame-tofu,[2 blocks firm or extra firm tofu (anywhere fr...,"[firm or extra firm tofu, cornstarch, un-toast...","[Drain each block of tofu. Using your hands, g...","[6, Calories: 358kcal (18%), Carbohydrates: 29..."
2,pork-belly-char-siu,[2 pounds boneless skinless pork belly (if tri...,"[boneless skinless pork belly, granulated suga...","[If you have a larger piece of pork belly, cut...","[6, Calories: 682kcal (34%), Carbohydrates: 11..."
3,red-bean-zongzi,[2 pounds sweet rice (also known as sticky ric...,"[sweet rice, lye water, neutral oil, dried red...","[In a large, fine mesh strainer, rinse the swe...","[12, Calories: 344kcal (17%), Carbohydrates: 7..."
4,stir-fry-spinach,[1 pound spinach (preferably Taiwanese spinach...,"[spinach, neutral oil, garlic, Salt to taste, ...",[Wash spinach clean by soaking a few times and...,"[4, Calories: 130kcal (7%), Carbohydrates: 5g ..."

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1414 entries, 0 to 1413
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               1414 non-null   object
 1   Ingredients_List   1414 non-null   object
 2   Ingredients_Names  1414 non-null   object
 3   Procedure          1414 non-null   object
 4   Nutrition_Facts    1414 non-null   object
dtypes: object(5)
memory usage: 55.4+ KB

In [41]:
df.sample(3)

,Name,Ingredients_List,Ingredients_Names,Procedure,Nutrition_Facts
605,multigrain-congee,"[brown rice, brown sweet rice, black rice, bla...","[brown rice, brown sweet rice, black rice, bla...",[Soak the grains in water for 2 hours. You may...,[]
1301,perfect-baked-seasoned-fries,"[1 red onion (sliced about 1/4-inch thick), ½ ...","[red onion, whole black peppercorns, bay leaf,...","[In a small pot, add all the ingredients and s...",[4]
30,eggs-soy-bean-sauce,"[1½ tablespoons soybean sauce or hoisin sauce,...","[soybean sauce or hoisin sauce, sesame oil, li...",[Prepare the sauce by combining the soybean sa...,"[3, Calories: 265kcal (13%), Carbohydrates: 6g..."

#Save Data to CSV

In [42]:
output_file = "woks_of_life_recipes.csv"

df.to_csv(
    output_file,
    index=False,
    encoding="utf-8"
)

print(f"Output file: {output_file}")

Output file: woks_of_life_recipes.csv

In [ ]:
!ls

sample_data  woks_of_life_recipes.csv